#!/usr/bin/env bash
# vc-quick-cmd.sh — the ❯_ Quick cmd shell behind the compact-bar chip
#
# One shot unless this pane is pinned. Quick cmd is where short, often
# emergency commands are typed (decyzja Macieja 2026-10-05), so the loop is a
# real interactive zsh speaking the SAME completion and syntax-highlighting
# base as the product shell — not a bash `read -e` imitation that can only
# complete filenames. The pane sets VC_QUICK_CMD=1 and the product profile's
# Quick lane then skips the tool chrome: no Atuin daemon, no Starship prompt,
# no zoxide hooks; built-in Up/Down recall and Ctrl+R incremental search stay.
#
# The one-shot rule lives in zsh hooks: preexec arms after a real command,
# precmd prints [exit N] on failure, probes pin state and closes an unpinned
# pane by id; `exit` and Ctrl-D close through zshexit. Ctrl-C stops only the
# running command (or clears an empty prompt); it does not kill this shell.
#
# Never `close-pane` without `--pane-id`. A bare close-pane follows focus and
# would kill whichever pane holds it — including a durable Agent the command
# just spawned in another tab. Missing pane-id: leave without guessing.
# Pin state is `vc-frame action list-panes --json --state`: the entry whose
# id matches this pane, field `is_pinned`. A repeated id prefers the terminal
# pane over a plugin. Missing field, CLI, parser, or pane-id means unpinned.
set -euo pipefail

export VIBECRAFTED_QUIET_START=1
export VC_QUICK_CMD=1

_pane="${VC_FRAME_PANE_ID:-${ZELLIJ_PANE_ID:-}}"
export VC_QUICK_PANE_ID="${_pane}"

# Whole lines, exactly as the Founder wrote the first one. The second line
# used to promise "Ctrl+N anytime", which does not open a tab — the truthful
# affordance is the [+] button in the tab bar (zgłoszenie Macieja 2026-10-05).
printf '%s\n' \
  'This is one shot ephemeral shell unless you PIN ● it. Type command and forget.' \
  'You can open a real shell by pressing [+] in the tab bar anytime.'

# The Quick lane ZDOTDIR is product state, regenerated on every launch so an
# updated runtime never leaves a stale hook behind.
_zdot="${VIBECRAFTED_HOME:-$HOME/.vibecrafted}/shell/quick-cmd"
mkdir -p "${_zdot}"
cat > "${_zdot}/.zshrc" <<'ZSHRC'
# Generated by vc-quick-cmd.sh on every launch. Do not edit.

# Same base as the product terminal: completions, autosuggestions, syntax
# highlighting, aliases. The VC_QUICK_CMD lane inside the profile skips
# Atuin/Starship/zoxide init for this pane.
_vc_quick_profile="$HOME/.config/vibecrafted/vc-terminal/interactive.zsh"
[[ ! -r "${_vc_quick_profile}" ]] || source "${_vc_quick_profile}"

# Quick cmd identity prompt; the profile's offline fallback is for full panes.
PROMPT='❯_ '
RPROMPT=''

# Prints "pinned" or "unpinned". Never fails the caller.
_vc_quick_pin_state() {
  if [[ -z "${VC_QUICK_PANE_ID:-}" ]]; then
    print -r -- unpinned
    return 0
  fi
  if ! command -v vc-frame >/dev/null 2>&1 || ! command -v python3 >/dev/null 2>&1; then
    print -r -- unpinned
    return 0
  fi
  local raw
  if ! raw="$(vc-frame action list-panes --json --state 2>/dev/null)"; then
    print -r -- unpinned
    return 0
  fi
  # The heredoc is python's program (stdin). The JSON rides in argv so it
  # is not swallowed by that redirection.
  python3 - "${raw}" <<'PY'
import json
import os
import sys

target = os.environ.get("VC_QUICK_PANE_ID", "")
raw = sys.argv[1] if len(sys.argv) > 1 else ""
raw = raw.strip()


def pane_id(value):
    if isinstance(value, bool) or value is None:
        return ""
    return str(value)


def pinned_flag(node):
    if "is_pinned" not in node:
        return None
    value = node.get("is_pinned")
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return value != 0
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes"}
    return False


matches = []


def walk(node):
    if isinstance(node, dict):
        if pane_id(node.get("id")) == target:
            matches.append(node)
        for value in node.values():
            walk(value)
    elif isinstance(node, list):
        for value in node:
            walk(value)


try:
    payload = json.loads(raw) if raw else None
except Exception:
    payload = None
if payload is not None and target:
    walk(payload)

chosen = [node for node in matches if node.get("is_plugin") is not True]
if not chosen:
    chosen = matches
flag = None
for node in chosen:
    state = pinned_flag(node)
    if state is True:
        flag = True
        break
    if state is False:
        flag = False
print("pinned" if flag is True else "unpinned")
PY
}

_vc_quick_close_self() {
  if [[ -z "${VC_QUICK_PANE_ID:-}" ]]; then
    return 0
  fi
  command -v vc-frame >/dev/null 2>&1 || return 0
  vc-frame action close-pane --pane-id "${VC_QUICK_PANE_ID}" >/dev/null 2>&1 || true
}

# Ctrl-C clears the prompt line or stops the running child; it must never
# kill this shell (also when stdin is not a tty, where zsh's default would).
TRAPINT() { return $(( 128 + $1 )) }

# One-shot rule. preexec arms only for an accepted, non-empty command line,
# so Ctrl-C or Enter at an empty prompt never counts as the one shot.
typeset -g _vc_quick_ran=0
_vc_quick_preexec() { _vc_quick_ran=1 }
_vc_quick_precmd() {
  # `status` is zsh's read-only alias of $?; capture under our own name.
  local _vc_quick_last=$?
  (( _vc_quick_ran )) || return 0
  _vc_quick_ran=0
  if (( _vc_quick_last != 0 )); then
    printf '[exit %d]\n' "${_vc_quick_last}"
  fi
  local state
  state="$(_vc_quick_pin_state)" || state=unpinned
  if [[ "${state}" != pinned ]]; then
    exit 0
  fi
}
autoload -Uz add-zsh-hook
add-zsh-hook preexec _vc_quick_preexec
add-zsh-hook precmd _vc_quick_precmd

# Every way out — one-shot close, typed `exit`, Ctrl-D — releases the pane.
zshexit() { _vc_quick_close_self }
ZSHRC

ZDOTDIR="${_zdot}" exec zsh -l -i
