// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(vibecrafted_shell_ffiFFI)
import vibecrafted_shell_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_vibecrafted_shell_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_vibecrafted_shell_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureVibecraftedShellFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct FfiActionQueueItem: Equatable, Hashable {
    public var kind: FfiActionQueueKind
    public var summary: String
    public var sourcePath: String?
    public var priority: FfiActionPriority

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: FfiActionQueueKind, summary: String, sourcePath: String?, priority: FfiActionPriority) {
        self.kind = kind
        self.summary = summary
        self.sourcePath = sourcePath
        self.priority = priority
    }


}

#if compiler(>=6)
extension FfiActionQueueItem: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiActionQueueItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiActionQueueItem {
        return
            try FfiActionQueueItem(
                kind: FfiConverterTypeFfiActionQueueKind.read(from: &buf),
                summary: FfiConverterString.read(from: &buf),
                sourcePath: FfiConverterOptionString.read(from: &buf),
                priority: FfiConverterTypeFfiActionPriority.read(from: &buf)
        )
    }

    public static func write(_ value: FfiActionQueueItem, into buf: inout [UInt8]) {
        FfiConverterTypeFfiActionQueueKind.write(value.kind, into: &buf)
        FfiConverterString.write(value.summary, into: &buf)
        FfiConverterOptionString.write(value.sourcePath, into: &buf)
        FfiConverterTypeFfiActionPriority.write(value.priority, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiActionQueueItem_lift(_ buf: RustBuffer) throws -> FfiActionQueueItem {
    return try FfiConverterTypeFfiActionQueueItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiActionQueueItem_lower(_ value: FfiActionQueueItem) -> RustBuffer {
    return FfiConverterTypeFfiActionQueueItem.lower(value)
}


public struct FfiActiveDispatch: Equatable, Hashable {
    public var runId: String
    public var agent: String
    public var skill: String
    public var wave: String?
    public var startedAt: String?
    public var ageLabel: String
    public var etaLabel: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(runId: String, agent: String, skill: String, wave: String?, startedAt: String?, ageLabel: String, etaLabel: String) {
        self.runId = runId
        self.agent = agent
        self.skill = skill
        self.wave = wave
        self.startedAt = startedAt
        self.ageLabel = ageLabel
        self.etaLabel = etaLabel
    }


}

#if compiler(>=6)
extension FfiActiveDispatch: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiActiveDispatch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiActiveDispatch {
        return
            try FfiActiveDispatch(
                runId: FfiConverterString.read(from: &buf),
                agent: FfiConverterString.read(from: &buf),
                skill: FfiConverterString.read(from: &buf),
                wave: FfiConverterOptionString.read(from: &buf),
                startedAt: FfiConverterOptionString.read(from: &buf),
                ageLabel: FfiConverterString.read(from: &buf),
                etaLabel: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiActiveDispatch, into buf: inout [UInt8]) {
        FfiConverterString.write(value.runId, into: &buf)
        FfiConverterString.write(value.agent, into: &buf)
        FfiConverterString.write(value.skill, into: &buf)
        FfiConverterOptionString.write(value.wave, into: &buf)
        FfiConverterOptionString.write(value.startedAt, into: &buf)
        FfiConverterString.write(value.ageLabel, into: &buf)
        FfiConverterString.write(value.etaLabel, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiActiveDispatch_lift(_ buf: RustBuffer) throws -> FfiActiveDispatch {
    return try FfiConverterTypeFfiActiveDispatch.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiActiveDispatch_lower(_ value: FfiActiveDispatch) -> RustBuffer {
    return FfiConverterTypeFfiActiveDispatch.lower(value)
}


public struct FfiAgentStatsRow: Equatable, Hashable {
    public var agent: String
    public var totalRuns: UInt32
    public var completed: UInt32
    public var failed: UInt32
    public var successRate: Float
    /**
     * Average duration in seconds. None when no upstream meta.json
     * carried `duration_s`; the operator surface should render an
     * explicit `—` rather than zero.
     */
    public var avgDurationS: Double?
    public var modelKnownRate: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(agent: String, totalRuns: UInt32, completed: UInt32, failed: UInt32, successRate: Float,
        /**
         * Average duration in seconds. None when no upstream meta.json
         * carried `duration_s`; the operator surface should render an
         * explicit `—` rather than zero.
         */avgDurationS: Double?, modelKnownRate: Float) {
        self.agent = agent
        self.totalRuns = totalRuns
        self.completed = completed
        self.failed = failed
        self.successRate = successRate
        self.avgDurationS = avgDurationS
        self.modelKnownRate = modelKnownRate
    }


}

#if compiler(>=6)
extension FfiAgentStatsRow: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAgentStatsRow: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAgentStatsRow {
        return
            try FfiAgentStatsRow(
                agent: FfiConverterString.read(from: &buf),
                totalRuns: FfiConverterUInt32.read(from: &buf),
                completed: FfiConverterUInt32.read(from: &buf),
                failed: FfiConverterUInt32.read(from: &buf),
                successRate: FfiConverterFloat.read(from: &buf),
                avgDurationS: FfiConverterOptionDouble.read(from: &buf),
                modelKnownRate: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAgentStatsRow, into buf: inout [UInt8]) {
        FfiConverterString.write(value.agent, into: &buf)
        FfiConverterUInt32.write(value.totalRuns, into: &buf)
        FfiConverterUInt32.write(value.completed, into: &buf)
        FfiConverterUInt32.write(value.failed, into: &buf)
        FfiConverterFloat.write(value.successRate, into: &buf)
        FfiConverterOptionDouble.write(value.avgDurationS, into: &buf)
        FfiConverterFloat.write(value.modelKnownRate, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAgentStatsRow_lift(_ buf: RustBuffer) throws -> FfiAgentStatsRow {
    return try FfiConverterTypeFfiAgentStatsRow.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAgentStatsRow_lower(_ value: FfiAgentStatsRow) -> RustBuffer {
    return FfiConverterTypeFfiAgentStatsRow.lower(value)
}


public struct FfiClientConfig: Equatable, Hashable {
    public var kind: FfiClientKind
    public var config: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: FfiClientKind, config: String) {
        self.kind = kind
        self.config = config
    }


}

#if compiler(>=6)
extension FfiClientConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiClientConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiClientConfig {
        return
            try FfiClientConfig(
                kind: FfiConverterTypeFfiClientKind.read(from: &buf),
                config: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiClientConfig, into buf: inout [UInt8]) {
        FfiConverterTypeFfiClientKind.write(value.kind, into: &buf)
        FfiConverterString.write(value.config, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClientConfig_lift(_ buf: RustBuffer) throws -> FfiClientConfig {
    return try FfiConverterTypeFfiClientConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClientConfig_lower(_ value: FfiClientConfig) -> RustBuffer {
    return FfiConverterTypeFfiClientConfig.lower(value)
}


public struct FfiDataQuality: Equatable, Hashable {
    public var scannedMetaFiles: UInt32
    public var capped: Bool
    public var missingModel: UInt32
    public var missingDuration: UInt32
    public var parseFailures: UInt32
    public var artifactRoot: String?
    public var artifactRootPresent: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(scannedMetaFiles: UInt32, capped: Bool, missingModel: UInt32, missingDuration: UInt32, parseFailures: UInt32, artifactRoot: String?, artifactRootPresent: Bool) {
        self.scannedMetaFiles = scannedMetaFiles
        self.capped = capped
        self.missingModel = missingModel
        self.missingDuration = missingDuration
        self.parseFailures = parseFailures
        self.artifactRoot = artifactRoot
        self.artifactRootPresent = artifactRootPresent
    }


}

#if compiler(>=6)
extension FfiDataQuality: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDataQuality: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDataQuality {
        return
            try FfiDataQuality(
                scannedMetaFiles: FfiConverterUInt32.read(from: &buf),
                capped: FfiConverterBool.read(from: &buf),
                missingModel: FfiConverterUInt32.read(from: &buf),
                missingDuration: FfiConverterUInt32.read(from: &buf),
                parseFailures: FfiConverterUInt32.read(from: &buf),
                artifactRoot: FfiConverterOptionString.read(from: &buf),
                artifactRootPresent: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiDataQuality, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.scannedMetaFiles, into: &buf)
        FfiConverterBool.write(value.capped, into: &buf)
        FfiConverterUInt32.write(value.missingModel, into: &buf)
        FfiConverterUInt32.write(value.missingDuration, into: &buf)
        FfiConverterUInt32.write(value.parseFailures, into: &buf)
        FfiConverterOptionString.write(value.artifactRoot, into: &buf)
        FfiConverterBool.write(value.artifactRootPresent, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDataQuality_lift(_ buf: RustBuffer) throws -> FfiDataQuality {
    return try FfiConverterTypeFfiDataQuality.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDataQuality_lower(_ value: FfiDataQuality) -> RustBuffer {
    return FfiConverterTypeFfiDataQuality.lower(value)
}


public struct FfiFailureEntry: Equatable, Hashable {
    public var runId: String
    public var agent: String
    public var skill: String
    public var reason: String
    public var occurredAt: String?
    public var ageLabel: String
    /**
     * Absolute filesystem path to the source artifact (meta.json or
     * report.md) when known. Shell-side surfaces should treat absence
     * as "no permalink available" rather than synthesizing one.
     */
    public var sourcePath: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(runId: String, agent: String, skill: String, reason: String, occurredAt: String?, ageLabel: String,
        /**
         * Absolute filesystem path to the source artifact (meta.json or
         * report.md) when known. Shell-side surfaces should treat absence
         * as "no permalink available" rather than synthesizing one.
         */sourcePath: String?) {
        self.runId = runId
        self.agent = agent
        self.skill = skill
        self.reason = reason
        self.occurredAt = occurredAt
        self.ageLabel = ageLabel
        self.sourcePath = sourcePath
    }


}

#if compiler(>=6)
extension FfiFailureEntry: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiFailureEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiFailureEntry {
        return
            try FfiFailureEntry(
                runId: FfiConverterString.read(from: &buf),
                agent: FfiConverterString.read(from: &buf),
                skill: FfiConverterString.read(from: &buf),
                reason: FfiConverterString.read(from: &buf),
                occurredAt: FfiConverterOptionString.read(from: &buf),
                ageLabel: FfiConverterString.read(from: &buf),
                sourcePath: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiFailureEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.runId, into: &buf)
        FfiConverterString.write(value.agent, into: &buf)
        FfiConverterString.write(value.skill, into: &buf)
        FfiConverterString.write(value.reason, into: &buf)
        FfiConverterOptionString.write(value.occurredAt, into: &buf)
        FfiConverterString.write(value.ageLabel, into: &buf)
        FfiConverterOptionString.write(value.sourcePath, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFailureEntry_lift(_ buf: RustBuffer) throws -> FfiFailureEntry {
    return try FfiConverterTypeFfiFailureEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFailureEntry_lower(_ value: FfiFailureEntry) -> RustBuffer {
    return FfiConverterTypeFfiFailureEntry.lower(value)
}


public struct FfiFleetHealthSignal: Equatable, Hashable {
    public var label: String
    public var status: FfiFleetHealthStatus
    public var detail: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(label: String, status: FfiFleetHealthStatus, detail: String) {
        self.label = label
        self.status = status
        self.detail = detail
    }


}

#if compiler(>=6)
extension FfiFleetHealthSignal: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiFleetHealthSignal: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiFleetHealthSignal {
        return
            try FfiFleetHealthSignal(
                label: FfiConverterString.read(from: &buf),
                status: FfiConverterTypeFfiFleetHealthStatus.read(from: &buf),
                detail: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiFleetHealthSignal, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterTypeFfiFleetHealthStatus.write(value.status, into: &buf)
        FfiConverterString.write(value.detail, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFleetHealthSignal_lift(_ buf: RustBuffer) throws -> FfiFleetHealthSignal {
    return try FfiConverterTypeFfiFleetHealthSignal.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFleetHealthSignal_lower(_ value: FfiFleetHealthSignal) -> RustBuffer {
    return FfiConverterTypeFfiFleetHealthSignal.lower(value)
}


public struct FfiMissionControlSnapshot: Equatable, Hashable {
    public var generatedAt: String
    public var activeDispatches: [FfiActiveDispatch]
    public var waveAtlas: [FfiWaveSegment]
    public var agentStats: [FfiAgentStatsRow]
    public var skillStats: [FfiSkillStatsRow]
    public var settlement: FfiSettlementBoard
    public var fleetHealth: [FfiFleetHealthSignal]
    public var failures: [FfiFailureEntry]
    public var actionQueue: [FfiActionQueueItem]
    public var dataQuality: FfiDataQuality

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(generatedAt: String, activeDispatches: [FfiActiveDispatch], waveAtlas: [FfiWaveSegment], agentStats: [FfiAgentStatsRow], skillStats: [FfiSkillStatsRow], settlement: FfiSettlementBoard, fleetHealth: [FfiFleetHealthSignal], failures: [FfiFailureEntry], actionQueue: [FfiActionQueueItem], dataQuality: FfiDataQuality) {
        self.generatedAt = generatedAt
        self.activeDispatches = activeDispatches
        self.waveAtlas = waveAtlas
        self.agentStats = agentStats
        self.skillStats = skillStats
        self.settlement = settlement
        self.fleetHealth = fleetHealth
        self.failures = failures
        self.actionQueue = actionQueue
        self.dataQuality = dataQuality
    }


}

#if compiler(>=6)
extension FfiMissionControlSnapshot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMissionControlSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMissionControlSnapshot {
        return
            try FfiMissionControlSnapshot(
                generatedAt: FfiConverterString.read(from: &buf),
                activeDispatches: FfiConverterSequenceTypeFfiActiveDispatch.read(from: &buf),
                waveAtlas: FfiConverterSequenceTypeFfiWaveSegment.read(from: &buf),
                agentStats: FfiConverterSequenceTypeFfiAgentStatsRow.read(from: &buf),
                skillStats: FfiConverterSequenceTypeFfiSkillStatsRow.read(from: &buf),
                settlement: FfiConverterTypeFfiSettlementBoard.read(from: &buf),
                fleetHealth: FfiConverterSequenceTypeFfiFleetHealthSignal.read(from: &buf),
                failures: FfiConverterSequenceTypeFfiFailureEntry.read(from: &buf),
                actionQueue: FfiConverterSequenceTypeFfiActionQueueItem.read(from: &buf),
                dataQuality: FfiConverterTypeFfiDataQuality.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMissionControlSnapshot, into buf: inout [UInt8]) {
        FfiConverterString.write(value.generatedAt, into: &buf)
        FfiConverterSequenceTypeFfiActiveDispatch.write(value.activeDispatches, into: &buf)
        FfiConverterSequenceTypeFfiWaveSegment.write(value.waveAtlas, into: &buf)
        FfiConverterSequenceTypeFfiAgentStatsRow.write(value.agentStats, into: &buf)
        FfiConverterSequenceTypeFfiSkillStatsRow.write(value.skillStats, into: &buf)
        FfiConverterTypeFfiSettlementBoard.write(value.settlement, into: &buf)
        FfiConverterSequenceTypeFfiFleetHealthSignal.write(value.fleetHealth, into: &buf)
        FfiConverterSequenceTypeFfiFailureEntry.write(value.failures, into: &buf)
        FfiConverterSequenceTypeFfiActionQueueItem.write(value.actionQueue, into: &buf)
        FfiConverterTypeFfiDataQuality.write(value.dataQuality, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMissionControlSnapshot_lift(_ buf: RustBuffer) throws -> FfiMissionControlSnapshot {
    return try FfiConverterTypeFfiMissionControlSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMissionControlSnapshot_lower(_ value: FfiMissionControlSnapshot) -> RustBuffer {
    return FfiConverterTypeFfiMissionControlSnapshot.lower(value)
}


public struct FfiNonMuxEntry: Equatable, Hashable {
    public var name: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String) {
        self.name = name
    }


}

#if compiler(>=6)
extension FfiNonMuxEntry: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiNonMuxEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiNonMuxEntry {
        return
            try FfiNonMuxEntry(
                name: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiNonMuxEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNonMuxEntry_lift(_ buf: RustBuffer) throws -> FfiNonMuxEntry {
    return try FfiConverterTypeFfiNonMuxEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNonMuxEntry_lower(_ value: FfiNonMuxEntry) -> RustBuffer {
    return FfiConverterTypeFfiNonMuxEntry.lower(value)
}


public struct FfiRoute: Equatable, Hashable {
    public var client: FfiClientKind
    public var service: String
    public var state: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(client: FfiClientKind, service: String, state: String) {
        self.client = client
        self.service = service
        self.state = state
    }


}

#if compiler(>=6)
extension FfiRoute: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRoute: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRoute {
        return
            try FfiRoute(
                client: FfiConverterTypeFfiClientKind.read(from: &buf),
                service: FfiConverterString.read(from: &buf),
                state: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRoute, into buf: inout [UInt8]) {
        FfiConverterTypeFfiClientKind.write(value.client, into: &buf)
        FfiConverterString.write(value.service, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRoute_lift(_ buf: RustBuffer) throws -> FfiRoute {
    return try FfiConverterTypeFfiRoute.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRoute_lower(_ value: FfiRoute) -> RustBuffer {
    return FfiConverterTypeFfiRoute.lower(value)
}


public struct FfiRunDetail: Equatable, Hashable {
    public var runId: String
    public var agent: String?
    public var skill: String?
    public var state: String?
    public var reportMd: String?
    public var transcriptTail: String
    public var reportPath: String?
    public var transcriptPath: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(runId: String, agent: String?, skill: String?, state: String?, reportMd: String?, transcriptTail: String, reportPath: String?, transcriptPath: String?) {
        self.runId = runId
        self.agent = agent
        self.skill = skill
        self.state = state
        self.reportMd = reportMd
        self.transcriptTail = transcriptTail
        self.reportPath = reportPath
        self.transcriptPath = transcriptPath
    }


}

#if compiler(>=6)
extension FfiRunDetail: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRunDetail: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRunDetail {
        return
            try FfiRunDetail(
                runId: FfiConverterString.read(from: &buf),
                agent: FfiConverterOptionString.read(from: &buf),
                skill: FfiConverterOptionString.read(from: &buf),
                state: FfiConverterOptionString.read(from: &buf),
                reportMd: FfiConverterOptionString.read(from: &buf),
                transcriptTail: FfiConverterString.read(from: &buf),
                reportPath: FfiConverterOptionString.read(from: &buf),
                transcriptPath: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRunDetail, into buf: inout [UInt8]) {
        FfiConverterString.write(value.runId, into: &buf)
        FfiConverterOptionString.write(value.agent, into: &buf)
        FfiConverterOptionString.write(value.skill, into: &buf)
        FfiConverterOptionString.write(value.state, into: &buf)
        FfiConverterOptionString.write(value.reportMd, into: &buf)
        FfiConverterString.write(value.transcriptTail, into: &buf)
        FfiConverterOptionString.write(value.reportPath, into: &buf)
        FfiConverterOptionString.write(value.transcriptPath, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRunDetail_lift(_ buf: RustBuffer) throws -> FfiRunDetail {
    return try FfiConverterTypeFfiRunDetail.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRunDetail_lower(_ value: FfiRunDetail) -> RustBuffer {
    return FfiConverterTypeFfiRunDetail.lower(value)
}


public struct FfiServerStatus: Equatable, Hashable {
    public var name: String
    public var status: String
    public var queueDepth: UInt32
    public var queueCapacity: UInt32
    public var restartCount: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, status: String, queueDepth: UInt32, queueCapacity: UInt32, restartCount: UInt64) {
        self.name = name
        self.status = status
        self.queueDepth = queueDepth
        self.queueCapacity = queueCapacity
        self.restartCount = restartCount
    }


}

#if compiler(>=6)
extension FfiServerStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiServerStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiServerStatus {
        return
            try FfiServerStatus(
                name: FfiConverterString.read(from: &buf),
                status: FfiConverterString.read(from: &buf),
                queueDepth: FfiConverterUInt32.read(from: &buf),
                queueCapacity: FfiConverterUInt32.read(from: &buf),
                restartCount: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiServerStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterUInt32.write(value.queueDepth, into: &buf)
        FfiConverterUInt32.write(value.queueCapacity, into: &buf)
        FfiConverterUInt64.write(value.restartCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiServerStatus_lift(_ buf: RustBuffer) throws -> FfiServerStatus {
    return try FfiConverterTypeFfiServerStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiServerStatus_lower(_ value: FfiServerStatus) -> RustBuffer {
    return FfiConverterTypeFfiServerStatus.lower(value)
}


public struct FfiSettlementBoard: Equatable, Hashable {
    public var f: UInt64
    public var x: UInt64
    public var n: UInt64
    public var invalid: UInt64
    public var unclassified: UInt64
    public var active: UInt64
    public var stalled: UInt64
    public var orphans: UInt64
    public var totalSettled: UInt64
    public var scope: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(f: UInt64, x: UInt64, n: UInt64, invalid: UInt64, unclassified: UInt64, active: UInt64, stalled: UInt64, orphans: UInt64, totalSettled: UInt64, scope: String) {
        self.f = f
        self.x = x
        self.n = n
        self.invalid = invalid
        self.unclassified = unclassified
        self.active = active
        self.stalled = stalled
        self.orphans = orphans
        self.totalSettled = totalSettled
        self.scope = scope
    }


}

#if compiler(>=6)
extension FfiSettlementBoard: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSettlementBoard: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSettlementBoard {
        return
            try FfiSettlementBoard(
                f: FfiConverterUInt64.read(from: &buf),
                x: FfiConverterUInt64.read(from: &buf),
                n: FfiConverterUInt64.read(from: &buf),
                invalid: FfiConverterUInt64.read(from: &buf),
                unclassified: FfiConverterUInt64.read(from: &buf),
                active: FfiConverterUInt64.read(from: &buf),
                stalled: FfiConverterUInt64.read(from: &buf),
                orphans: FfiConverterUInt64.read(from: &buf),
                totalSettled: FfiConverterUInt64.read(from: &buf),
                scope: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSettlementBoard, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.f, into: &buf)
        FfiConverterUInt64.write(value.x, into: &buf)
        FfiConverterUInt64.write(value.n, into: &buf)
        FfiConverterUInt64.write(value.invalid, into: &buf)
        FfiConverterUInt64.write(value.unclassified, into: &buf)
        FfiConverterUInt64.write(value.active, into: &buf)
        FfiConverterUInt64.write(value.stalled, into: &buf)
        FfiConverterUInt64.write(value.orphans, into: &buf)
        FfiConverterUInt64.write(value.totalSettled, into: &buf)
        FfiConverterString.write(value.scope, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSettlementBoard_lift(_ buf: RustBuffer) throws -> FfiSettlementBoard {
    return try FfiConverterTypeFfiSettlementBoard.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSettlementBoard_lower(_ value: FfiSettlementBoard) -> RustBuffer {
    return FfiConverterTypeFfiSettlementBoard.lower(value)
}


public struct FfiSkillStatsRow: Equatable, Hashable {
    public var skill: String
    public var invocations: UInt32
    public var completed: UInt32
    public var failed: UInt32
    public var avgDurationS: Double?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(skill: String, invocations: UInt32, completed: UInt32, failed: UInt32, avgDurationS: Double?) {
        self.skill = skill
        self.invocations = invocations
        self.completed = completed
        self.failed = failed
        self.avgDurationS = avgDurationS
    }


}

#if compiler(>=6)
extension FfiSkillStatsRow: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSkillStatsRow: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSkillStatsRow {
        return
            try FfiSkillStatsRow(
                skill: FfiConverterString.read(from: &buf),
                invocations: FfiConverterUInt32.read(from: &buf),
                completed: FfiConverterUInt32.read(from: &buf),
                failed: FfiConverterUInt32.read(from: &buf),
                avgDurationS: FfiConverterOptionDouble.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSkillStatsRow, into buf: inout [UInt8]) {
        FfiConverterString.write(value.skill, into: &buf)
        FfiConverterUInt32.write(value.invocations, into: &buf)
        FfiConverterUInt32.write(value.completed, into: &buf)
        FfiConverterUInt32.write(value.failed, into: &buf)
        FfiConverterOptionDouble.write(value.avgDurationS, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSkillStatsRow_lift(_ buf: RustBuffer) throws -> FfiSkillStatsRow {
    return try FfiConverterTypeFfiSkillStatsRow.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSkillStatsRow_lower(_ value: FfiSkillStatsRow) -> RustBuffer {
    return FfiConverterTypeFfiSkillStatsRow.lower(value)
}


public struct FfiVerifyResult: Equatable, Hashable {
    public var kind: FfiClientKind
    public var ok: Bool
    public var detail: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: FfiClientKind, ok: Bool, detail: String) {
        self.kind = kind
        self.ok = ok
        self.detail = detail
    }


}

#if compiler(>=6)
extension FfiVerifyResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiVerifyResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiVerifyResult {
        return
            try FfiVerifyResult(
                kind: FfiConverterTypeFfiClientKind.read(from: &buf),
                ok: FfiConverterBool.read(from: &buf),
                detail: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiVerifyResult, into buf: inout [UInt8]) {
        FfiConverterTypeFfiClientKind.write(value.kind, into: &buf)
        FfiConverterBool.write(value.ok, into: &buf)
        FfiConverterString.write(value.detail, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiVerifyResult_lift(_ buf: RustBuffer) throws -> FfiVerifyResult {
    return try FfiConverterTypeFfiVerifyResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiVerifyResult_lower(_ value: FfiVerifyResult) -> RustBuffer {
    return FfiConverterTypeFfiVerifyResult.lower(value)
}


public struct FfiWaveSegment: Equatable, Hashable {
    public var waveId: String
    public var total: UInt32
    public var completed: UInt32
    public var failed: UInt32
    public var active: UInt32
    public var latestState: FfiWaveState

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(waveId: String, total: UInt32, completed: UInt32, failed: UInt32, active: UInt32, latestState: FfiWaveState) {
        self.waveId = waveId
        self.total = total
        self.completed = completed
        self.failed = failed
        self.active = active
        self.latestState = latestState
    }


}

#if compiler(>=6)
extension FfiWaveSegment: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiWaveSegment: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiWaveSegment {
        return
            try FfiWaveSegment(
                waveId: FfiConverterString.read(from: &buf),
                total: FfiConverterUInt32.read(from: &buf),
                completed: FfiConverterUInt32.read(from: &buf),
                failed: FfiConverterUInt32.read(from: &buf),
                active: FfiConverterUInt32.read(from: &buf),
                latestState: FfiConverterTypeFfiWaveState.read(from: &buf)
        )
    }

    public static func write(_ value: FfiWaveSegment, into buf: inout [UInt8]) {
        FfiConverterString.write(value.waveId, into: &buf)
        FfiConverterUInt32.write(value.total, into: &buf)
        FfiConverterUInt32.write(value.completed, into: &buf)
        FfiConverterUInt32.write(value.failed, into: &buf)
        FfiConverterUInt32.write(value.active, into: &buf)
        FfiConverterTypeFfiWaveState.write(value.latestState, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiWaveSegment_lift(_ buf: RustBuffer) throws -> FfiWaveSegment {
    return try FfiConverterTypeFfiWaveSegment.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiWaveSegment_lower(_ value: FfiWaveSegment) -> RustBuffer {
    return FfiConverterTypeFfiWaveSegment.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiActionPriority: Equatable, Hashable {

    case critical
    case high
    case normal



}

#if compiler(>=6)
extension FfiActionPriority: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiActionPriority: FfiConverterRustBuffer {
    typealias SwiftType = FfiActionPriority

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiActionPriority {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .critical

        case 2: return .high

        case 3: return .normal

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiActionPriority, into buf: inout [UInt8]) {
        switch value {


        case .critical:
            writeInt(&buf, Int32(1))


        case .high:
            writeInt(&buf, Int32(2))


        case .normal:
            writeInt(&buf, Int32(3))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiActionPriority_lift(_ buf: RustBuffer) throws -> FfiActionPriority {
    return try FfiConverterTypeFfiActionPriority.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiActionPriority_lower(_ value: FfiActionPriority) -> RustBuffer {
    return FfiConverterTypeFfiActionPriority.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiActionQueueKind: Equatable, Hashable {

    case stalledRun
    case failure
    case polarize
    case reportReady



}

#if compiler(>=6)
extension FfiActionQueueKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiActionQueueKind: FfiConverterRustBuffer {
    typealias SwiftType = FfiActionQueueKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiActionQueueKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .stalledRun

        case 2: return .failure

        case 3: return .polarize

        case 4: return .reportReady

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiActionQueueKind, into buf: inout [UInt8]) {
        switch value {


        case .stalledRun:
            writeInt(&buf, Int32(1))


        case .failure:
            writeInt(&buf, Int32(2))


        case .polarize:
            writeInt(&buf, Int32(3))


        case .reportReady:
            writeInt(&buf, Int32(4))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiActionQueueKind_lift(_ buf: RustBuffer) throws -> FfiActionQueueKind {
    return try FfiConverterTypeFfiActionQueueKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiActionQueueKind_lower(_ value: FfiActionQueueKind) -> RustBuffer {
    return FfiConverterTypeFfiActionQueueKind.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiClientKind: Equatable, Hashable {

    case claude
    case codex
    case gemini
    case junie
    case cursor
    case generic(name: String
    )



}

#if compiler(>=6)
extension FfiClientKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiClientKind: FfiConverterRustBuffer {
    typealias SwiftType = FfiClientKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiClientKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .claude

        case 2: return .codex

        case 3: return .gemini

        case 4: return .junie

        case 5: return .cursor

        case 6: return .generic(name: try FfiConverterString.read(from: &buf)
        )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiClientKind, into buf: inout [UInt8]) {
        switch value {


        case .claude:
            writeInt(&buf, Int32(1))


        case .codex:
            writeInt(&buf, Int32(2))


        case .gemini:
            writeInt(&buf, Int32(3))


        case .junie:
            writeInt(&buf, Int32(4))


        case .cursor:
            writeInt(&buf, Int32(5))


        case let .generic(name):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(name, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClientKind_lift(_ buf: RustBuffer) throws -> FfiClientKind {
    return try FfiConverterTypeFfiClientKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClientKind_lower(_ value: FfiClientKind) -> RustBuffer {
    return FfiConverterTypeFfiClientKind.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiFleetHealthStatus: Equatable, Hashable {

    case ok
    case warn
    case blocked
    case unknown



}

#if compiler(>=6)
extension FfiFleetHealthStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiFleetHealthStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiFleetHealthStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiFleetHealthStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .ok

        case 2: return .warn

        case 3: return .blocked

        case 4: return .unknown

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiFleetHealthStatus, into buf: inout [UInt8]) {
        switch value {


        case .ok:
            writeInt(&buf, Int32(1))


        case .warn:
            writeInt(&buf, Int32(2))


        case .blocked:
            writeInt(&buf, Int32(3))


        case .unknown:
            writeInt(&buf, Int32(4))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFleetHealthStatus_lift(_ buf: RustBuffer) throws -> FfiFleetHealthStatus {
    return try FfiConverterTypeFfiFleetHealthStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFleetHealthStatus_lower(_ value: FfiFleetHealthStatus) -> RustBuffer {
    return FfiConverterTypeFfiFleetHealthStatus.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiSubscriberState: Equatable, Hashable {

    case connected
    case disconnected



}

#if compiler(>=6)
extension FfiSubscriberState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSubscriberState: FfiConverterRustBuffer {
    typealias SwiftType = FfiSubscriberState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSubscriberState {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .connected

        case 2: return .disconnected

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiSubscriberState, into buf: inout [UInt8]) {
        switch value {


        case .connected:
            writeInt(&buf, Int32(1))


        case .disconnected:
            writeInt(&buf, Int32(2))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSubscriberState_lift(_ buf: RustBuffer) throws -> FfiSubscriberState {
    return try FfiConverterTypeFfiSubscriberState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSubscriberState_lower(_ value: FfiSubscriberState) -> RustBuffer {
    return FfiConverterTypeFfiSubscriberState.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiWaveState: Equatable, Hashable {

    case pending
    case inProgress
    case completed
    case failed



}

#if compiler(>=6)
extension FfiWaveState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiWaveState: FfiConverterRustBuffer {
    typealias SwiftType = FfiWaveState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiWaveState {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .pending

        case 2: return .inProgress

        case 3: return .completed

        case 4: return .failed

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiWaveState, into buf: inout [UInt8]) {
        switch value {


        case .pending:
            writeInt(&buf, Int32(1))


        case .inProgress:
            writeInt(&buf, Int32(2))


        case .completed:
            writeInt(&buf, Int32(3))


        case .failed:
            writeInt(&buf, Int32(4))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiWaveState_lift(_ buf: RustBuffer) throws -> FfiWaveState {
    return try FfiConverterTypeFfiWaveState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiWaveState_lower(_ value: FfiWaveState) -> RustBuffer {
    return FfiConverterTypeFfiWaveState.lower(value)
}



public enum MuxError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    case Core(msg: String
    )




    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension MuxError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMuxError: FfiConverterRustBuffer {
    typealias SwiftType = MuxError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MuxError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Core(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MuxError, into buf: inout [UInt8]) {
        switch value {





        case let .Core(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMuxError_lift(_ buf: RustBuffer) throws -> MuxError {
    return try FfiConverterTypeMuxError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMuxError_lower(_ value: MuxError) -> RustBuffer {
    return FfiConverterTypeMuxError.lower(value)
}




public protocol EventCallback: AnyObject, Sendable {

    func onEvent(eventJson: String)

    func onError(err: String)

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEventCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceEventCallback] = [UniffiVTableCallbackInterfaceEventCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceEventCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface EventCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceEventCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface EventCallback: handle missing in uniffiClone")
            }
        },
        onEvent: { (
            uniffiHandle: UInt64,
            eventJson: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     eventJson: try FfiConverterString.lift(eventJson)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            err: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onError(
                     err: try FfiConverterString.lift(err)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitEventCallback() {
    uniffi_vibecrafted_shell_ffi_fn_init_callback_vtable_eventcallback(UniffiCallbackInterfaceEventCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceEventCallback {
    fileprivate static let handleMap = UniffiHandleMap<EventCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceEventCallback : FfiConverter {
    typealias SwiftType = EventCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceEventCallback_lift(_ handle: UInt64) throws -> EventCallback {
    return try FfiConverterCallbackInterfaceEventCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceEventCallback_lower(_ v: EventCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceEventCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiActionQueueItem: FfiConverterRustBuffer {
    typealias SwiftType = [FfiActionQueueItem]

    public static func write(_ value: [FfiActionQueueItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiActionQueueItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiActionQueueItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiActionQueueItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiActionQueueItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiActiveDispatch: FfiConverterRustBuffer {
    typealias SwiftType = [FfiActiveDispatch]

    public static func write(_ value: [FfiActiveDispatch], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiActiveDispatch.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiActiveDispatch] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiActiveDispatch]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiActiveDispatch.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiAgentStatsRow: FfiConverterRustBuffer {
    typealias SwiftType = [FfiAgentStatsRow]

    public static func write(_ value: [FfiAgentStatsRow], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiAgentStatsRow.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiAgentStatsRow] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiAgentStatsRow]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiAgentStatsRow.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiFailureEntry: FfiConverterRustBuffer {
    typealias SwiftType = [FfiFailureEntry]

    public static func write(_ value: [FfiFailureEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiFailureEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiFailureEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiFailureEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiFailureEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiFleetHealthSignal: FfiConverterRustBuffer {
    typealias SwiftType = [FfiFleetHealthSignal]

    public static func write(_ value: [FfiFleetHealthSignal], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiFleetHealthSignal.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiFleetHealthSignal] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiFleetHealthSignal]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiFleetHealthSignal.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiRoute: FfiConverterRustBuffer {
    typealias SwiftType = [FfiRoute]

    public static func write(_ value: [FfiRoute], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiRoute.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiRoute] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiRoute]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiRoute.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiServerStatus: FfiConverterRustBuffer {
    typealias SwiftType = [FfiServerStatus]

    public static func write(_ value: [FfiServerStatus], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiServerStatus.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiServerStatus] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiServerStatus]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiServerStatus.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiSkillStatsRow: FfiConverterRustBuffer {
    typealias SwiftType = [FfiSkillStatsRow]

    public static func write(_ value: [FfiSkillStatsRow], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiSkillStatsRow.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiSkillStatsRow] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiSkillStatsRow]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiSkillStatsRow.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiWaveSegment: FfiConverterRustBuffer {
    typealias SwiftType = [FfiWaveSegment]

    public static func write(_ value: [FfiWaveSegment], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiWaveSegment.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiWaveSegment] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiWaveSegment]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiWaveSegment.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureVibecraftedShellFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func getRecentLogs(service: String, lines: UInt32)async throws  -> [String]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_get_recent_logs(FfiConverterString.lower(service),FfiConverterUInt32.lower(lines)
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceString.lift,
            errorHandler: FfiConverterTypeMuxError_lift
        )
}
public func getRoutes()async throws  -> [FfiRoute]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_get_routes(
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiRoute.lift,
            errorHandler: FfiConverterTypeMuxError_lift
        )
}
public func getServerStatus()async throws  -> [FfiServerStatus]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_get_server_status(
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiServerStatus.lift,
            errorHandler: FfiConverterTypeMuxError_lift
        )
}
public func initRuntime(socketPath: String)throws   {try rustCallWithError(FfiConverterTypeMuxError_lift) {
    uniffi_vibecrafted_shell_ffi_fn_func_init_runtime(
        FfiConverterString.lower(socketPath),$0
    )
}
}
/**
 * Load the operator's Mission Control snapshot using the default
 * resolution: control-plane root under `VIBECRAFTED_HOME` and artifact
 * root at `$VIBECRAFTED_HOME/artifacts/`.
 *
 * Shell surfaces (Swift/macOS app) should call this on focus / refresh
 * and bind directly to the returned record. Missing inputs surface as
 * typed empty states, never as panics.
 */
public func loadMissionControlSnapshot()throws  -> FfiMissionControlSnapshot  {
    return try  FfiConverterTypeFfiMissionControlSnapshot_lift(try rustCallWithError(FfiConverterTypeMuxError_lift) {
    uniffi_vibecrafted_shell_ffi_fn_func_load_mission_control_snapshot($0
    )
})
}
/**
 * Variant for surfaces that already resolved their own roots (tests,
 * agents that run in vendored workspaces, multi-tenant probing).
 */
public func loadMissionControlSnapshotAt(stateRoot: String, artifactRoot: String)throws  -> FfiMissionControlSnapshot  {
    return try  FfiConverterTypeFfiMissionControlSnapshot_lift(try rustCallWithError(FfiConverterTypeMuxError_lift) {
    uniffi_vibecrafted_shell_ffi_fn_func_load_mission_control_snapshot_at(
        FfiConverterString.lower(stateRoot),
        FfiConverterString.lower(artifactRoot),$0
    )
})
}
/**
 * Load one run's drill-down artifacts using the default control-plane root
 * (`default_state_root()` => `~/.vibecrafted/control_plane`). The inspector
 * calls this when a run is selected anywhere in Mission Control. Missing
 * inputs (no meta, no report, no transcript) surface as typed-empty, never a
 * panic.
 */
public func loadRunDetail(runId: String)throws  -> FfiRunDetail  {
    return try  FfiConverterTypeFfiRunDetail_lift(try rustCallWithError(FfiConverterTypeMuxError_lift) {
    uniffi_vibecrafted_shell_ffi_fn_func_load_run_detail(
        FfiConverterString.lower(runId),$0
    )
})
}
/**
 * Variant for surfaces that already resolved their own control-plane root
 * (tests, vendored workspaces). Mirrors `load_mission_control_snapshot_at`.
 */
public func loadRunDetailAt(stateRoot: String, runId: String)throws  -> FfiRunDetail  {
    return try  FfiConverterTypeFfiRunDetail_lift(try rustCallWithError(FfiConverterTypeMuxError_lift) {
    uniffi_vibecrafted_shell_ffi_fn_func_load_run_detail_at(
        FfiConverterString.lower(stateRoot),
        FfiConverterString.lower(runId),$0
    )
})
}
public func restartService(name: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_restart_service(FfiConverterString.lower(name)
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_void,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_void,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeMuxError_lift
        )
}
public func subscribeEvents(callback: EventCallback)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_subscribe_events(FfiConverterCallbackInterfaceEventCallback_lower(callback)
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_void,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_void,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeMuxError_lift
        )
}
public func verifyClient(kind: FfiClientKind)async throws  -> FfiVerifyResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_verify_client(FfiConverterTypeFfiClientKind_lower(kind)
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFfiVerifyResult_lift,
            errorHandler: FfiConverterTypeMuxError_lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_vibecrafted_shell_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_get_recent_logs() != 12164) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_get_routes() != 40408) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_get_server_status() != 17348) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_init_runtime() != 22518) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_load_mission_control_snapshot() != 40441) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_load_mission_control_snapshot_at() != 11312) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_load_run_detail() != 9516) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_load_run_detail_at() != 24709) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_restart_service() != 60065) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_subscribe_events() != 65076) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_verify_client() != 11223) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_method_eventcallback_on_event() != 6295) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_method_eventcallback_on_error() != 16499) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitEventCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureVibecraftedShellFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all