// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(vibecrafted_shell_ffiFFI)
import vibecrafted_shell_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_vibecrafted_shell_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_vibecrafted_shell_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureVibecraftedShellFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct FfiClientConfig: Equatable, Hashable {
    public var kind: FfiClientKind
    public var config: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: FfiClientKind, config: String) {
        self.kind = kind
        self.config = config
    }


}

#if compiler(>=6)
extension FfiClientConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiClientConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiClientConfig {
        return
            try FfiClientConfig(
                kind: FfiConverterTypeFfiClientKind.read(from: &buf),
                config: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiClientConfig, into buf: inout [UInt8]) {
        FfiConverterTypeFfiClientKind.write(value.kind, into: &buf)
        FfiConverterString.write(value.config, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClientConfig_lift(_ buf: RustBuffer) throws -> FfiClientConfig {
    return try FfiConverterTypeFfiClientConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClientConfig_lower(_ value: FfiClientConfig) -> RustBuffer {
    return FfiConverterTypeFfiClientConfig.lower(value)
}


public struct FfiNonMuxEntry: Equatable, Hashable {
    public var name: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String) {
        self.name = name
    }


}

#if compiler(>=6)
extension FfiNonMuxEntry: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiNonMuxEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiNonMuxEntry {
        return
            try FfiNonMuxEntry(
                name: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiNonMuxEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNonMuxEntry_lift(_ buf: RustBuffer) throws -> FfiNonMuxEntry {
    return try FfiConverterTypeFfiNonMuxEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNonMuxEntry_lower(_ value: FfiNonMuxEntry) -> RustBuffer {
    return FfiConverterTypeFfiNonMuxEntry.lower(value)
}


public struct FfiRoute: Equatable, Hashable {
    public var client: FfiClientKind
    public var service: String
    public var state: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(client: FfiClientKind, service: String, state: String) {
        self.client = client
        self.service = service
        self.state = state
    }


}

#if compiler(>=6)
extension FfiRoute: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRoute: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRoute {
        return
            try FfiRoute(
                client: FfiConverterTypeFfiClientKind.read(from: &buf),
                service: FfiConverterString.read(from: &buf),
                state: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRoute, into buf: inout [UInt8]) {
        FfiConverterTypeFfiClientKind.write(value.client, into: &buf)
        FfiConverterString.write(value.service, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRoute_lift(_ buf: RustBuffer) throws -> FfiRoute {
    return try FfiConverterTypeFfiRoute.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRoute_lower(_ value: FfiRoute) -> RustBuffer {
    return FfiConverterTypeFfiRoute.lower(value)
}


public struct FfiServerStatus: Equatable, Hashable {
    public var name: String
    public var status: String
    public var queueDepth: UInt32
    public var queueCapacity: UInt32
    public var restartCount: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, status: String, queueDepth: UInt32, queueCapacity: UInt32, restartCount: UInt64) {
        self.name = name
        self.status = status
        self.queueDepth = queueDepth
        self.queueCapacity = queueCapacity
        self.restartCount = restartCount
    }


}

#if compiler(>=6)
extension FfiServerStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiServerStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiServerStatus {
        return
            try FfiServerStatus(
                name: FfiConverterString.read(from: &buf),
                status: FfiConverterString.read(from: &buf),
                queueDepth: FfiConverterUInt32.read(from: &buf),
                queueCapacity: FfiConverterUInt32.read(from: &buf),
                restartCount: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiServerStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterUInt32.write(value.queueDepth, into: &buf)
        FfiConverterUInt32.write(value.queueCapacity, into: &buf)
        FfiConverterUInt64.write(value.restartCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiServerStatus_lift(_ buf: RustBuffer) throws -> FfiServerStatus {
    return try FfiConverterTypeFfiServerStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiServerStatus_lower(_ value: FfiServerStatus) -> RustBuffer {
    return FfiConverterTypeFfiServerStatus.lower(value)
}


public struct FfiVerifyResult: Equatable, Hashable {
    public var kind: FfiClientKind
    public var ok: Bool
    public var detail: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: FfiClientKind, ok: Bool, detail: String) {
        self.kind = kind
        self.ok = ok
        self.detail = detail
    }


}

#if compiler(>=6)
extension FfiVerifyResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiVerifyResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiVerifyResult {
        return
            try FfiVerifyResult(
                kind: FfiConverterTypeFfiClientKind.read(from: &buf),
                ok: FfiConverterBool.read(from: &buf),
                detail: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiVerifyResult, into buf: inout [UInt8]) {
        FfiConverterTypeFfiClientKind.write(value.kind, into: &buf)
        FfiConverterBool.write(value.ok, into: &buf)
        FfiConverterString.write(value.detail, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiVerifyResult_lift(_ buf: RustBuffer) throws -> FfiVerifyResult {
    return try FfiConverterTypeFfiVerifyResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiVerifyResult_lower(_ value: FfiVerifyResult) -> RustBuffer {
    return FfiConverterTypeFfiVerifyResult.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiClientKind: Equatable, Hashable {

    case claude
    case codex
    case gemini
    case junie
    case generic(name: String
    )



}

#if compiler(>=6)
extension FfiClientKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiClientKind: FfiConverterRustBuffer {
    typealias SwiftType = FfiClientKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiClientKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .claude

        case 2: return .codex

        case 3: return .gemini

        case 4: return .junie

        case 5: return .generic(name: try FfiConverterString.read(from: &buf)
        )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiClientKind, into buf: inout [UInt8]) {
        switch value {


        case .claude:
            writeInt(&buf, Int32(1))


        case .codex:
            writeInt(&buf, Int32(2))


        case .gemini:
            writeInt(&buf, Int32(3))


        case .junie:
            writeInt(&buf, Int32(4))


        case let .generic(name):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(name, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClientKind_lift(_ buf: RustBuffer) throws -> FfiClientKind {
    return try FfiConverterTypeFfiClientKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClientKind_lower(_ value: FfiClientKind) -> RustBuffer {
    return FfiConverterTypeFfiClientKind.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiSubscriberState: Equatable, Hashable {

    case connected
    case disconnected



}

#if compiler(>=6)
extension FfiSubscriberState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSubscriberState: FfiConverterRustBuffer {
    typealias SwiftType = FfiSubscriberState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSubscriberState {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .connected

        case 2: return .disconnected

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiSubscriberState, into buf: inout [UInt8]) {
        switch value {


        case .connected:
            writeInt(&buf, Int32(1))


        case .disconnected:
            writeInt(&buf, Int32(2))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSubscriberState_lift(_ buf: RustBuffer) throws -> FfiSubscriberState {
    return try FfiConverterTypeFfiSubscriberState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSubscriberState_lower(_ value: FfiSubscriberState) -> RustBuffer {
    return FfiConverterTypeFfiSubscriberState.lower(value)
}



public enum MuxError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    case Core(msg: String
    )




    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension MuxError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMuxError: FfiConverterRustBuffer {
    typealias SwiftType = MuxError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MuxError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Core(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MuxError, into buf: inout [UInt8]) {
        switch value {





        case let .Core(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMuxError_lift(_ buf: RustBuffer) throws -> MuxError {
    return try FfiConverterTypeMuxError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMuxError_lower(_ value: MuxError) -> RustBuffer {
    return FfiConverterTypeMuxError.lower(value)
}




public protocol EventCallback: AnyObject, Sendable {

    func onEvent(eventJson: String)

    func onError(err: String)

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEventCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceEventCallback] = [UniffiVTableCallbackInterfaceEventCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceEventCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface EventCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceEventCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface EventCallback: handle missing in uniffiClone")
            }
        },
        onEvent: { (
            uniffiHandle: UInt64,
            eventJson: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     eventJson: try FfiConverterString.lift(eventJson)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onError: { (
            uniffiHandle: UInt64,
            err: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceEventCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onError(
                     err: try FfiConverterString.lift(err)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitEventCallback() {
    uniffi_vibecrafted_shell_ffi_fn_init_callback_vtable_eventcallback(UniffiCallbackInterfaceEventCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceEventCallback {
    fileprivate static let handleMap = UniffiHandleMap<EventCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceEventCallback : FfiConverter {
    typealias SwiftType = EventCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceEventCallback_lift(_ handle: UInt64) throws -> EventCallback {
    return try FfiConverterCallbackInterfaceEventCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceEventCallback_lower(_ v: EventCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceEventCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiRoute: FfiConverterRustBuffer {
    typealias SwiftType = [FfiRoute]

    public static func write(_ value: [FfiRoute], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiRoute.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiRoute] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiRoute]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiRoute.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiServerStatus: FfiConverterRustBuffer {
    typealias SwiftType = [FfiServerStatus]

    public static func write(_ value: [FfiServerStatus], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiServerStatus.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiServerStatus] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiServerStatus]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiServerStatus.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureVibecraftedShellFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func getRecentLogs(service: String, lines: UInt32)async throws  -> [String]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_get_recent_logs(FfiConverterString.lower(service),FfiConverterUInt32.lower(lines)
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceString.lift,
            errorHandler: FfiConverterTypeMuxError_lift
        )
}
public func getRoutes()async throws  -> [FfiRoute]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_get_routes(
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiRoute.lift,
            errorHandler: FfiConverterTypeMuxError_lift
        )
}
public func getServerStatus()async throws  -> [FfiServerStatus]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_get_server_status(
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiServerStatus.lift,
            errorHandler: FfiConverterTypeMuxError_lift
        )
}
public func initRuntime(socketPath: String)throws   {try rustCallWithError(FfiConverterTypeMuxError_lift) {
    uniffi_vibecrafted_shell_ffi_fn_func_init_runtime(
        FfiConverterString.lower(socketPath),$0
    )
}
}
public func restartService(name: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_restart_service(FfiConverterString.lower(name)
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_void,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_void,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeMuxError_lift
        )
}
public func subscribeEvents(callback: EventCallback)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_subscribe_events(FfiConverterCallbackInterfaceEventCallback_lower(callback)
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_void,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_void,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeMuxError_lift
        )
}
public func verifyClient(kind: FfiClientKind)async throws  -> FfiVerifyResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_vibecrafted_shell_ffi_fn_func_verify_client(FfiConverterTypeFfiClientKind_lower(kind)
                )
            },
            pollFunc: ffi_vibecrafted_shell_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_vibecrafted_shell_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_vibecrafted_shell_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFfiVerifyResult_lift,
            errorHandler: FfiConverterTypeMuxError_lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_vibecrafted_shell_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_get_recent_logs() != 12164) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_get_routes() != 40408) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_get_server_status() != 17348) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_init_runtime() != 22518) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_restart_service() != 60065) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_subscribe_events() != 65076) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_func_verify_client() != 11223) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_method_eventcallback_on_event() != 6295) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vibecrafted_shell_ffi_checksum_method_eventcallback_on_error() != 16499) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitEventCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureVibecraftedShellFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all