"""Installer for the vibecrafted iTerm2 / locterm integration.

Run from the host Python env:

    python -m vibecrafted_iterm2.install_autolaunch
    python -m vibecrafted_iterm2.install_autolaunch --uninstall

The installer:

* Creates ``~/Library/Application Support/iTerm2/Scripts/AutoLaunch/`` if
  missing.
* Symlinks ``vc_launcher.py`` into that AutoLaunch directory so iTerm2
  picks it up next boot. We use a symlink — not a copy — so plugin
  upgrades just need a ``pip install -U`` on the host venv.
* Writes ``~/Library/Application Support/iTerm2/DynamicProfiles/vibecrafted.json``
  with the managed Vibecrafted trigger profile.
* Writes a sibling ``uninstall_vc_launcher.sh`` that removes both owned
  artifacts cleanly without touching anything else.
* Prints the next-step user instructions (toggle Python API in iTerm2
  Preferences if needed).

GPL boundary: this installer ships only as part of vibecrafted, drops a
single symlink into iTerm2's AutoLaunch directory, and never modifies
iTerm2 / locterm source. The separation matches the FSF guidance for
"mere aggregation" of GPL'd and non-GPL'd software.
"""

from __future__ import annotations

import argparse
import os
import sys
from collections.abc import Iterable
from pathlib import Path
from textwrap import dedent

from . import iterm2_profiles

AUTOLAUNCH_RELPATH = Path("Library/Application Support/iTerm2/Scripts/AutoLaunch")
LAUNCHER_FILENAME = "vc_launcher.py"
UNINSTALL_SCRIPT = "uninstall_vc_launcher.sh"
DYNAMIC_PROFILES_RELPATH = Path("Library/Application Support/iTerm2/DynamicProfiles")


def autolaunch_dir(home: Path | None = None) -> Path:
    """Resolve iTerm2's per-user AutoLaunch scripts directory under `home`."""
    base = home or Path.home()
    return base / AUTOLAUNCH_RELPATH


def dynamic_profiles_dir(home: Path | None = None) -> Path:
    """Resolve iTerm2's per-user DynamicProfiles directory under `home`."""
    base = home or Path.home()
    return base / DYNAMIC_PROFILES_RELPATH


def launcher_source() -> Path:
    """Path to the bundled vc_launcher.py inside this installed package."""
    return Path(__file__).resolve().parent / LAUNCHER_FILENAME


def iterm2_app_candidates(home: Path | None = None) -> tuple[Path, ...]:
    """List candidate iTerm2/locterm .app paths, env override first."""
    base = home or Path.home()
    env_override = os.environ.get("VIBECRAFTED_ITERM2_APP")
    candidates = []
    if env_override:
        candidates.append(Path(env_override).expanduser())
    candidates.extend(
        (
            Path("/Applications/iTerm.app"),
            Path("/Applications/locterm.app"),
            base / "Applications/iTerm.app",
            base / "Applications/locterm.app",
        )
    )
    return tuple(candidates)


def find_iterm2_app(
    candidates: Iterable[str | Path] | None = None,
) -> str | None:
    """Return the first existing terminal app path from `candidates`, or None."""
    candidates = candidates or iterm2_app_candidates()
    for raw in candidates:
        path = Path(raw).expanduser()
        if path.exists():
            return str(path)
    return None


def install(*, home: Path | None = None, force: bool = False) -> Path:
    """Symlink vc_launcher.py into iTerm2's AutoLaunch directory.

    Returns the destination path. Raises ``FileNotFoundError`` if the
    launcher source disappears underneath us, and ``FileExistsError`` if
    the destination already exists and ``force`` is False.
    """
    target_dir = autolaunch_dir(home)
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / LAUNCHER_FILENAME

    src = launcher_source()
    if not src.exists():
        raise FileNotFoundError(f"vc_launcher.py source missing at {src}")

    if target.exists() or target.is_symlink():
        if not force:
            raise FileExistsError(f"{target} already exists; pass --force to replace")
        target.unlink()

    profile_target = iterm2_profiles.install_profiles(
        target_dir=dynamic_profiles_dir(home),
        force=force,
    )
    target.symlink_to(src)
    _write_uninstaller(target_dir, target, profile_target)
    return target


def _write_uninstaller(target_dir: Path, target: Path, profile_target: Path) -> Path:
    """Generate and chmod the self-removing uninstall_vc_launcher.sh script."""
    uninstaller = target_dir / UNINSTALL_SCRIPT
    body = dedent(
        f"""\
        #!/usr/bin/env bash
        # Auto-generated by vibecrafted-iterm2 installer.
        # Removes only the Vibecrafted-owned AutoLaunch and DynamicProfiles files.
        set -euo pipefail
        if [ -L "{target}" ] || [ -e "{target}" ]; then
          rm -f "{target}"
          echo "removed {target}"
        else
          echo "nothing to remove at {target}"
        fi
        if [ -e "{profile_target}" ]; then
          rm -f "{profile_target}"
          echo "removed {profile_target}"
        else
          echo "nothing to remove at {profile_target}"
        fi
        rm -f "$0"
        """
    )
    uninstaller.write_text(body, encoding="utf-8")
    uninstaller.chmod(0o755)
    return uninstaller


def uninstall(*, home: Path | None = None) -> bool:
    """Remove the AutoLaunch symlink, uninstall script, and DynamicProfile.

    Returns True if anything was actually removed.
    """
    removed = False
    target = autolaunch_dir(home) / LAUNCHER_FILENAME
    if target.exists() or target.is_symlink():
        target.unlink()
        removed = True
    uninstaller = autolaunch_dir(home) / UNINSTALL_SCRIPT
    if uninstaller.exists() or uninstaller.is_symlink():
        uninstaller.unlink()
        removed = True
    if iterm2_profiles.uninstall_profiles(target_dir=dynamic_profiles_dir(home)):
        removed = True
    return removed


def _print_next_steps(target: Path, iterm2_app: str | None) -> None:
    """Print post-install user instructions to stdout."""
    where = iterm2_app or "iTerm2 (or locterm) not detected in /Applications"
    print(
        dedent(
            f"""
            vibecrafted AutoLaunch installed:
                {target}
            DynamicProfile installed:
                {dynamic_profiles_dir() / iterm2_profiles.DEFAULT_FILENAME}

            Detected terminal app: {where}

            Next steps (one-time):
              1. Open iTerm2 / locterm.
              2. Preferences → General → Magic → Enable Python API.
              3. Restart iTerm2 / locterm.
              4. The vibecrafted status bar component will appear in
                 Preferences → Profiles → Session → Status Bar → Components.
                 Drag "vibecrafted" onto your status bar to surface
                 live spawn activity.
              5. Select the "Vibecrafted" profile when you want the managed
                 trigger rows. Your default profile was not modified.

            To uninstall later, run:
              bash "{autolaunch_dir() / UNINSTALL_SCRIPT}"
            """
        )
    )


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: install or --uninstall the AutoLaunch plugin."""
    parser = argparse.ArgumentParser(
        description="Install or remove the vibecrafted iTerm2 / locterm AutoLaunch plugin."
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="Remove the AutoLaunch symlink instead of installing it.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an existing AutoLaunch symlink without asking.",
    )
    args = parser.parse_args(argv)

    if args.uninstall:
        removed = uninstall()
        print("removed" if removed else "no AutoLaunch symlink to remove")
        return 0

    try:
        target = install(force=args.force)
    except FileExistsError as exc:
        sys.stderr.write(f"{exc}\n")
        return 1
    except OSError as exc:
        sys.stderr.write(f"install failed: {exc}\n")
        return 1

    _print_next_steps(target, find_iterm2_app())
    if os.environ.get("VIBECRAFTED_DEV") == "1":
        print("[dev] launcher source:", launcher_source())
    return 0


if __name__ == "__main__":  # CLI entry point
    raise SystemExit(main())
