#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF_USAGE'
Usage: install-shell.sh [--source <repo-root>] [--dry-run] [--no-zshrc] [--no-bashrc]

Install the 𝚅𝚒𝚋𝚎𝚌𝚛𝚊𝚏𝚝𝚎𝚍. shell helper layer. The helpers work in both bash and zsh.
By default, sources the helper from $HOME/.bashrc and $HOME/.zshrc for shells that are
available. Use --no-zshrc or --no-bashrc to skip a shell.
EOF_USAGE
}

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
dry_run=0
update_zshrc=1
update_bashrc=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source)
      shift
      [[ $# -gt 0 ]] || die "Missing value for --source"
      repo_root="$1"
      ;;
    --dry-run|-n)
      dry_run=1
      ;;
    --no-zshrc)
      update_zshrc=0
      ;;
    --no-bashrc)
      update_bashrc=0
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
  shift
done

# Find source file (new name first, then legacy)
source_file="$repo_root/skills/vc-agents/shell/vetcoders.sh"
[[ -f "$source_file" ]] || source_file="$repo_root/skills/vc-agents/shell/vetcoders.zsh"
[[ -f "$source_file" ]] || source_file="$repo_root/vc-agents/shell/vetcoders.sh"
[[ -f "$source_file" ]] || source_file="$repo_root/vc-agents/shell/vetcoders.zsh"
[[ -f "$source_file" ]] || die "Helper file not found"

# Canonical install location (shell-agnostic)
config_base="${XDG_CONFIG_HOME:-$HOME/.config}"
target_dir="$config_base/vetcoders"
target_file="$target_dir/vc-skills.sh"

# Legacy compat location for existing zsh installs
legacy_dir="$config_base/zsh"
legacy_file="$legacy_dir/vc-skills.zsh"

# Source line — same syntax works in both bash and zsh
# shellcheck disable=SC2016
source_line='[[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/vetcoders/vc-skills.sh" ]] && source "${XDG_CONFIG_HOME:-$HOME/.config}/vetcoders/vc-skills.sh"'

printf 'Installing 𝚅𝚒𝚋𝚎𝚌𝚛𝚊𝚏𝚝𝚎𝚍. shell helpers\n'
printf '  source: %s\n' "$source_file"
printf '  target: %s\n' "$target_file"

write_helper_shim() {
  cat > "$target_file" <<EOF_SHIM
# shellcheck shell=bash
# 𝚅𝚒𝚋𝚎𝚌𝚛𝚊𝚏𝚝𝚎𝚍. helper shim. Generated by install-shell.sh.

_vibecrafted_helper_candidates() {
  local crafted_home="\${VIBECRAFTED_HOME:-\$HOME/.vibecrafted}"
  if [[ -n "\${VIBECRAFTED_ROOT:-}" ]]; then
    printf '%s\n' "\$VIBECRAFTED_ROOT/skills/vc-agents/shell/vetcoders.sh"
    printf '%s\n' "\$VIBECRAFTED_ROOT/skills/vc-agents/shell/vetcoders.zsh"
  fi
  printf '%s\n' \
    "$repo_root/skills/vc-agents/shell/vetcoders.sh" \
    "$repo_root/skills/vc-agents/shell/vetcoders.zsh" \
    "\$crafted_home/tools/vibecrafted-current/skills/vc-agents/shell/vetcoders.sh" \
    "\$crafted_home/tools/vibecrafted-current/skills/vc-agents/shell/vetcoders.zsh" \
    "\$crafted_home/skills/vc-agents/shell/vetcoders.sh" \
    "\$crafted_home/skills/vc-agents/shell/vetcoders.zsh"
}

_vibecrafted_source_helper() {
  local helper
  while IFS= read -r helper; do
    [[ -n "\$helper" && -r "\$helper" ]] || continue
    # shellcheck disable=SC1090
    source "\$helper"
    return 0
  done < <(_vibecrafted_helper_candidates)

  printf 'Error: 𝚅𝚒𝚋𝚎𝚌𝚛𝚊𝚏𝚝𝚎𝚍. helper not found. Checked:\n' >&2
  _vibecrafted_helper_candidates | sed 's/^/  - /' >&2
  return 1
}

_vibecrafted_source_status=0
_vibecrafted_source_helper || _vibecrafted_source_status=\$?
unset -f _vibecrafted_helper_candidates _vibecrafted_source_helper
return "\$_vibecrafted_source_status" 2>/dev/null || exit "\$_vibecrafted_source_status"
EOF_SHIM
}

if (( dry_run )); then
  printf '  (dry run)\n'
else
  mkdir -p "$target_dir"
  write_helper_shim
  # Legacy compat symlink so old .zshrc source lines still work
  mkdir -p "$legacy_dir"
  ln -sfn "$target_file" "$legacy_file"
fi

_update_rcfile() {
  local rcfile="$1"
  # $2 = shell_name (for logging, currently unused)

  # Already present — nothing to do
  if [[ -f "$rcfile" ]] && grep -Fq "vetcoders/vc-skills.sh" "$rcfile"; then
    printf '  %s: already sourced\n' "$rcfile"
    return 0
  fi

  # Respect locked/immutable files
  if [[ -f "$rcfile" ]] && ! touch -c "$rcfile" 2>/dev/null; then
    printf '\033[33m[warn]\033[0m %s is locked — add manually:\n' "$rcfile"
    printf '       %s\n' "$source_line"
    return 0
  fi

  if (( dry_run )); then
    printf '  %s: would add source line\n' "$rcfile"
    return 0
  fi

  {
    printf '\n# 𝚅𝚒𝚋𝚎𝚌𝚛𝚊𝚏𝚝𝚎𝚍. shell helpers\n'
    printf '%s\n' "$source_line"
  } >> "$rcfile"

  printf '  %s: updated\n' "$rcfile"
}

rcfile_touched=0

if (( update_zshrc )); then
  if command -v zsh >/dev/null 2>&1 || [[ -f "$HOME/.zshrc" ]]; then
    _update_rcfile "$HOME/.zshrc" "zsh"
    rcfile_touched=1
  fi
fi

if (( update_bashrc )); then
  if [[ -f "$HOME/.bashrc" ]] || [[ "${SHELL##*/}" == "bash" ]]; then
    _update_rcfile "$HOME/.bashrc" "bash"
    rcfile_touched=1
  fi
fi

if (( ! rcfile_touched )); then
  printf '\033[33m[warn]\033[0m No shell rc file was updated automatically.\n'
  printf '       Add this line manually to the rc file you actually use:\n'
  printf '       %s\n' "$source_line"
fi
